version: "3.9"

services:
  postgres:
    image: postgres:18-alpine
    container_name: livraria-postgres
    environment:
      POSTGRES_DB: livrosdb
      POSTGRES_USER: livros
      POSTGRES_PASSWORD: livros
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: