spring:
  devtools:
    restart:
      enabled: false
  main.banner-mode: "OFF"
  threads.virtual.enabled: true
  application:
    name: LivrariaG

server:
  max-http-request-header-size: 128KB
  servlet:
    context-path: /
---

# Database.
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:livrosdb}
    username: ${SPRING_DATASOURCE_USERNAME:livros}
    password: ${SPRING_DATASOURCE_PASSWORD:livros}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    #locations: classpath:db/migration
    #validate-on-migrate: true
    #clean-disabled: true
  jpa:
    show-sql: false
    properties:
      hibernate:
        ddl-auto: validate
        format_sql: false

